name:                metapong
version:             0.1
github:              "simonmichael/metapong"
license:             GPL-3
author:              "Simon Michael"
maintainer:          "simon@joyful.com"
copyright:           "COPYRIGHT"

extra-source-files:
- README.md
- CHANGES.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web
description:         A pong-like video and meta game, owned by its player-contributors

dependencies:
- base               >= 4.9 && < 5
- ansi-terminal-game >= 1.8.1.0 && <1.9

executables:
  metapong:
    main:                metapong.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
