name:                metapong
version:             0.1
github:              "simonmichael/metapong"
license:             GPL-3
author:              "Simon Michael"
maintainer:          "simon@joyful.com"
copyright:           "COPYRIGHT"

extra-source-files:
- README.md
- CHANGES.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web
description:         Please see the README on GitHub at <https://github.com/simonmichael/metapong#readme>

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src

executables:
  metapong:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metapong

tests:
  metapong-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metapong
